# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SayHi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SayHi
  
  pod 'Firebase/Core', '~> 4.5.0'
  pod 'Firebase/Auth', '~> 4.5.0'
  pod 'Firebase/Database', '~> 4.5.0'
  
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'KeychainAccess', '~> 3.1.0'
  pod 'PromiseKit', '~> 4.4.3'
  pod 'SQLite.swift', '~> 0.11.4'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end
  
end
